version: 2.1

only_main: &only_main
  filters:
    branches:
      only: main

orbs:
  aws-cli: circleci/aws-cli@3.1.1

executors:
  node:
    docker: 
      - image: cimg/node:14.19

commands:
  npm_install:
    description: 'Install node modules'
    steps: 
      - run: npm ci
  sst_deploy:
    description: 'Deploy Serverless Stack'
    steps: 
      - run: npm run deploy

jobs:
  deploy:
    executor: node
    steps:
      - checkout
      - aws-cli/setup
      - npm_install
      - sst_deploy


workflows:
  version: 2
  deploy-prod:
    # <<: *only_main
    jobs:
      - deploy