version: 2.1

ignore_main: &ignore_main
  filters:
    branches:
      ignore: main

orbs:
  cypress: cypress-io/cypress@1

executors:
  node:
    docker: 
      - image: cimg/node:14.19

commands:
  install:
    description: 'Install node modules'
    steps: 
      - run: npm ci
  build:
    description: 'Install node modules'
    steps: 
      - run: npm build      
  deploy:
    description: 'Deploy Serverless Stack'
    steps: 
      - run: npm run deploy

references:
  workspace_root: &workspace_root .
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  setup:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: v0-deps-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}       
      - install
      - build
      - persist_to_workspace: # store this folder for other jobs
          root: *workspace_root
          paths:
            - . 

  deploy: 
    executor: node
    steps:
      - *attach_workspace
      - deploy

  test:
    steps:
      - *attach_workspace
      - cypress/run


workflows:
  version: 2
  deploy-prod:
    jobs:
      - setup:
          <<: *ignore_main
          context:
              - deploy_test    
      - deploy:
          <<: *ignore_main
          requires: 
            - setup
          context:
              - deploy_test
      - test:
          <<: *ignore_main
          requires: 
            - deploy        